version: "3.8"

services:
  app:
    image: saxenaaayush9000/traineeapi:latest
    container_name: spring-app
    restart: always
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://mappingdb.c1kqmqkg80ri.eu-north-1.rds.amazonaws.com:5432/mappingdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234567890
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
