spring.application.name=Project1
spring.datasource.url=jdbc:postgresql://db:5432/db
spring.datasource.username=postgres
spring.datasource.password=1234567890
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

server.port=8085
