spring.application.name=Project1
#spring.datasource.url=jdbc:postgresql://localhost:5432/MAPPINGDB
#spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/MAPPINGDB
#spring.datasource.username=postgres
#spring.datasource.password=1234567890

#using approch 2 of dockerpostgresl
#spring.datasource.url=jdbc:postgresql://postgres-db:5432/demoDB
#spring.datasource.username=admin
#spring.datasource.password=1234567890

#using approch 3 of dockerpostgresl
spring.datasource.url=${SPRING_DATABASE_URL}
spring.datasource.username=${SPRING_DATABASE_USERNAME}
spring.datasource.password=${SPRING_DATABASE_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create

server.port=8085