spring.application.name=Project1
spring.datasource.url=jdbc:postgresql://localhost:5432/MAPPINGDB
spring.datasource.username=postgres
spring.datasource.password=1234567890
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create

server.port=8085
